const SET_ALERT = 'SET_ALERT'
const REMOVE_ALERT = 'REMOVE_ALERT'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const REGISTER_FAIL = 'REGISTER_FAIL'
const USER_LOADED = 'USER_LOADED'
const AUTH_ERROR = 'AUTH_ERROR'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAIL = 'LOGIN_FAIL'
const LOG_OUT_USER = 'LOG_OUT_USER'
const GET_PROFILE = 'GET_PROFILE'
const GET_PROFILES = 'GET_PROFILES'
const GET_REPOS = 'GET_REPOS'
const PROFILE_ERROR = 'PROFILE_ERROR'
const CLEAR_PROFILE = 'CLEAR_PROFILE'
const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
const ADD_EDUCATION = 'ADD_EDUCATION'
const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE'
const DELETE_EDUCATION = 'DELETE_EDUCATION'
const DELETE_USER = 'DELETE_USER'
const GET_POST = 'GET_POST'
const POST_ERROR = 'POST_ERROR'
const GET_POSTS = 'GET_POSTS'

const constants = {
	SET_ALERT,
	REMOVE_ALERT,
	REGISTER_SUCCESS,
	REGISTER_FAIL,
	USER_LOADED,
	AUTH_ERROR,
	LOGIN_SUCCESS,
	LOGIN_FAIL,
	LOG_OUT_USER,
	GET_PROFILE,
	PROFILE_ERROR,
	CLEAR_PROFILE,
	ADD_EXPERIENCE,
	ADD_EDUCATION,
	DELETE_EXPERIENCE,
	DELETE_EDUCATION,
	DELETE_USER,
	GET_PROFILES,
	GET_REPOS,
	GET_POST,
	GET_POSTS,
	POST_ERROR,
	GET_POSTS,
}

export default constants
